public enum Teams {
    SIXERS, BUCKS, BULLS, CAVALIERS, CELTICS, CLIPPERS, GRIZZLIES, HAWKS, HEAT, HORNETS, JAZZ, KINGS, KNICKS, LAKERS, MAGIC, MAVERICKS, 
    NETS, NUGGETS, PACERS, PELICANS, PISTONS, RAPTORS, ROCKETS, SPURS, SUNS, THUNDER, TIMBERWOLVES, TRAILBLAZERS, WARRIORS, WIZARDS 
}
